### ISSUE TITLE
How to run agentx

### ISSUE THREAD

**Issue by ashish235** [pozgo/docker-snmpd#1]
Hi,

I was trying to setup net-snmp for agentx inside the container for my application. however I can't start the snmpd daemon. 

The host on which my container is running has an IP 172.16.111.195. Now my container's IP will  change everytime I bounce them so I can't configure the internal IP and also my snmp traps from my NMS need to communicate to the master agent on the host IP. So I 'm not able to figure out how do I map the agentx IP and port with the host

This is what I 'm getting in snmpd.logs.
Error: Couldn't open a master agentx socket to listen on (tcp:172.16.111.195:10705):

Looking forward to some help from you.

Thanks.

**Comment by pozgo** [comment]
HI... Can you include the commands that you are using to deploy those images? 

Im not sure if this is what you mean but you can specify `--link` when running docker image to link directly to it without a need or getting it's ip. 

Please see documentation [here](https://docs.docker.com/articles/networking/)

**Comment by ashish235** [comment]
Hi @pozgo, thanks for volunteering to help. I found the solution to the issue. 

Cheers!
